modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="frostpack"
version="1.0.0"
displayName="FrostPack"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="brune, MCreator"

[[dependencies.frostpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



